/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorSliderRoot: typeof import('reka-ui')['ColorSliderRoot']
    ColorSliderThumb: typeof import('reka-ui')['ColorSliderThumb']
    ColorSliderTrack: typeof import('reka-ui')['ColorSliderTrack']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./src/components/ui/SButton.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
