/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorSliderRoot: typeof import('reka-ui')['ColorSliderRoot']
    ColorSliderThumb: typeof import('reka-ui')['ColorSliderThumb']
    ColorSliderTrack: typeof import('reka-ui')['ColorSliderTrack']
    EffectsLyrics: typeof import('./src/components/player/EffectsLyrics/index.vue')['default']
    FullPlayer: typeof import('./src/components/player/FullPlayer/index.vue')['default']
    FullscreenPlayer: typeof import('./src/layouts/components/FullscreenPlayer.vue')['default']
    IconLucideAlignLeft: typeof import('~icons/lucide/align-left')['default']
    IconLucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    IconLucideCircleCheck: typeof import('~icons/lucide/circle-check')['default']
    IconLucideCircleX: typeof import('~icons/lucide/circle-x')['default']
    IconLucideColumns2: typeof import('~icons/lucide/columns2')['default']
    IconLucideInfo: typeof import('~icons/lucide/info')['default']
    IconLucideMessageCircle: typeof import('~icons/lucide/message-circle')['default']
    IconLucideMusic: typeof import('~icons/lucide/music')['default']
    IconLucidePause: typeof import('~icons/lucide/pause')['default']
    IconLucidePlay: typeof import('~icons/lucide/play')['default']
    IconLucideRepeat: typeof import('~icons/lucide/repeat')['default']
    IconLucideRepeat1: typeof import('~icons/lucide/repeat1')['default']
    IconLucideSave: typeof import('~icons/lucide/save')['default']
    IconLucideShuffle: typeof import('~icons/lucide/shuffle')['default']
    IconLucideSkipBack: typeof import('~icons/lucide/skip-back')['default']
    IconLucideSkipForward: typeof import('~icons/lucide/skip-forward')['default']
    IconLucideSquare: typeof import('~icons/lucide/square')['default']
    IconLucideTrash: typeof import('~icons/lucide/trash')['default']
    IconLucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    IconLucideVolume2: typeof import('~icons/lucide/volume2')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    NavHeader: typeof import('./src/layouts/components/NavHeader.vue')['default']
    PlayerBack: typeof import('./src/components/player/FullPlayer/PlayerBack.vue')['default']
    PlayerBackground: typeof import('./src/components/player/FullPlayer/PlayerBackground.vue')['default']
    PlayerBar: typeof import('./src/layouts/components/PlayerBar.vue')['default']
    PlayerCover: typeof import('./src/components/player/FullPlayer/PlayerCover.vue')['default']
    PopoverArrow: typeof import('reka-ui')['PopoverArrow']
    PopoverContent: typeof import('reka-ui')['PopoverContent']
    PopoverPortal: typeof import('reka-ui')['PopoverPortal']
    PopoverRoot: typeof import('reka-ui')['PopoverRoot']
    PopoverTrigger: typeof import('reka-ui')['PopoverTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./src/components/ui/SButton.vue')['default']
    SideBar: typeof import('./src/layouts/components/SideBar.vue')['default']
    SImg: typeof import('./src/components/ui/SImg.vue')['default']
    SLoading: typeof import('./src/components/ui/SLoading.vue')['default']
    SPopover: typeof import('./src/components/ui/SPopover.vue')['default']
    SToast: typeof import('./src/components/ui/SToast.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
