/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 清空封面（无歌曲时） */
export declare function clear(): void

/** 关闭自定义缩略图：撤销子类与 DWM 属性，恢复默认实时预览 */
export declare function disable(): void

/** 开启自定义缩略图：设置 DWM 属性并子类化窗口 */
export declare function enable(hwndPtr: number): boolean

/** 更新封面（BGRA、顶向下、不透明），并让 DWM 失效以重新拉取 */
export declare function setCover(bgra: Buffer, width: number, height: number): void
