/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 开启自定义缩略图：设置 DWM 属性并子类化窗口 */
export declare function enable(hwndPtr: number): boolean

/** 更新封面（BGRA、顶向下、不透明），并让 DWM 失效以重新拉取 */
export declare function setCover(bgra: Buffer, width: number, height: number): void
